//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutPlanes.DataAccess.CutPlanes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CutPlanesEntities : DbContext
    {
        public CutPlanesEntities()
            : base("name=CutPlanesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Constraint> Constraints { get; set; }
        public virtual DbSet<ConstraintSet> ConstraintSets { get; set; }
        public virtual DbSet<CutPlane> CutPlanes { get; set; }
        public virtual DbSet<CutPlaneType> CutPlaneTypes { get; set; }
        public virtual DbSet<DimCutPlaneSubstation> DimCutPlaneSubstations { get; set; }
        public virtual DbSet<DimCutPlaneTimePeriod> DimCutPlaneTimePeriods { get; set; }
        public virtual DbSet<DimLrbSubstation> DimLrbSubstations { get; set; }
        public virtual DbSet<LinkSubstationElectricalGroup> LinkSubstationElectricalGroups { get; set; }
        public virtual DbSet<MapType> MapTypes { get; set; }
        public virtual DbSet<Pool> Pools { get; set; }
        public virtual DbSet<PoolType> PoolTypes { get; set; }
        public virtual DbSet<SubstationAttribute> SubstationAttributes { get; set; }
        public virtual DbSet<Substation> Substations { get; set; }
        public virtual DbSet<SubstationType> SubstationTypes { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<ElectricalGroup> ElectricalGroups { get; set; }
        public virtual DbSet<LinkSubstationPool> LinkSubstationPools { get; set; }
    }
}
