//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutPlanes.DataAccess.CutPlanes
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimCutPlaneSubstation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string UserCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string SubtstaionType { get; set; }
        public string FuelType { get; set; }
        public string PrimaryPoi { get; set; }
        public string SecondaryPoi { get; set; }
        public Nullable<decimal> PoiVoltage { get; set; }
        public string PoiCircuitDesignation { get; set; }
        public string MapName { get; set; }
        public string MapDivisiion { get; set; }
        public string MapRegion { get; set; }
        public string MapSubRegion { get; set; }
        public string MapArea { get; set; }
        public string MapZone { get; set; }
    }
}
