//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutPlanes.DataAccess.CutPlanes
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkSubstationPool
    {
        public int Id { get; set; }
        public int SubstationId { get; set; }
        public int PoolId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserCreatedId { get; set; }
    }
}
