//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutPlanes.DataAccess.CutPlanes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pool
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserCreatedId { get; set; }
        public int CutPlaneId { get; set; }
        public int PoolTypeId { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> UserUpdatedId { get; set; }
    }
}
