//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutPlanes.DataAccess.CutPlanes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Substation
    {
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int UserCreatedId { get; set; }
        public Nullable<int> UserUpdatedId { get; set; }
        public Nullable<int> GeoLocationId { get; set; }
        public string Description { get; set; }
        public string SingleLineDiagramUri { get; set; }
        public string LocalOperationOrderLink { get; set; }
        public Nullable<int> MeterId { get; set; }
        public Nullable<int> ElectricalGroupId { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> PowerCallId { get; set; }
        public Nullable<bool> IsSynchronousCondenserCapable { get; set; }
        public Nullable<System.DateTime> CIMLoadTS { get; set; }
        public Nullable<System.DateTime> LRBLoadTS { get; set; }
        public Nullable<System.DateTime> FacilityLoadTS { get; set; }
        public Nullable<System.DateTime> NITSPlanLoadTS { get; set; }
        public Nullable<int> SubStationTypeId { get; set; }
        public Nullable<int> FuelTypeId { get; set; }
        public Nullable<int> OwnershipTypeId { get; set; }
        public Nullable<int> LTAPSubRegionId { get; set; }
        public Nullable<int> ResourceStatusId { get; set; }
        public string PrimaryPoi { get; set; }
        public string SecondaryPoi { get; set; }
        public string PoiCircuitDesignation { get; set; }
        public Nullable<decimal> PoiVoltage { get; set; }
        public string Name { get; set; }
        public string TLA { get; set; }
    }
}
