//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CutPlanes.DataAccess.CutPlanes
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubstationAttribute
    {
        public int Id { get; set; }
        public Nullable<int> OriginalId { get; set; }
        public Nullable<int> UserCreatedId { get; set; }
        public Nullable<int> UserUpdatedId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DateReplaced { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public Nullable<int> ProjectPhaseId { get; set; }
        public int SubstationId { get; set; }
        public int ResourcePlanId { get; set; }
        public Nullable<decimal> RatedMVA { get; set; }
        public Nullable<decimal> RatedOverExcitedPowerFactor { get; set; }
        public Nullable<decimal> RatedUnderExcitedPowerFactor { get; set; }
        public Nullable<decimal> NamePlateCapacityInMW { get; set; }
        public Nullable<decimal> RatedOverExcitedMvar { get; set; }
        public Nullable<decimal> RatedUnderExcitedMvar { get; set; }
        public Nullable<decimal> RatedPowerFactor { get; set; }
        public Nullable<decimal> DependableGeneratingCapacity { get; set; }
        public Nullable<decimal> EffectiveLoadCarryingCapacity { get; set; }
        public Nullable<decimal> LoadGrossSummerPeak { get; set; }
        public Nullable<decimal> LoadGrossSummerMin { get; set; }
        public Nullable<decimal> LoadGrossWinterPeak { get; set; }
        public Nullable<decimal> LoadGrossWinterMin { get; set; }
        public Nullable<decimal> MaximumPowerOutput { get; set; }
        public Nullable<bool> Nominated { get; set; }
        public Nullable<int> Probability { get; set; }
        public Nullable<System.DateTime> InServiceStartDate { get; set; }
        public Nullable<System.DateTime> InServiceEndDate { get; set; }
        public Nullable<decimal> NitsDesignatedCapacity { get; set; }
        public Nullable<decimal> EPACapacity { get; set; }
        public Nullable<decimal> MaxTakeOrPayCapacity { get; set; }
        public Nullable<decimal> PointToPointCapacity { get; set; }
        public Nullable<decimal> ReliabilityMustRunCapacity { get; set; }
        public Nullable<decimal> SystemCapacity { get; set; }
        public bool UsePdgcMasteredValue { get; set; }
        public bool UsePmpoMasteredValue { get; set; }
        public bool UsePptpMasteredValue { get; set; }
        public bool UsePrmrMasteredValue { get; set; }
        public bool UsePndcMasteredValue { get; set; }
        public bool UsePnpMasteredValue { get; set; }
        public bool UsePdmx0MasteredValue { get; set; }
        public bool UsePdmx1MasteredValue { get; set; }
        public Nullable<decimal> MaxOutputForFirmTransmission { get; set; }
        public Nullable<decimal> MaxOutputForNonFirmTransmission { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    }
}
